### ISSUE TITLE
Include more details about staking and the seat price

### ISSUE THREAD

**Issue by mikedotexe** [near/wiki#19]
Here's an update from Jane Wang from Nov 16th regarding the seat price. Would be good to distill it, ask her follow-up questions, and insert it into this section:
https://wiki.near.org/validator/validator-overview#for-validators

> After the protocol change goes in, the seat price is dynamically determined based on the 100th bid, but is always above 64,000 NEAR. It is unlikely that the seat price will stay exactly at 64,000 due to the competitive mechanism of bidding. As a thought experiment, if the seat price is at 64,000, someone could come in and bid 64,001 and gain a seat. The seat price is now 64,001. This process continues until an equilibrium is reached where the seat price is high enough such that no new entrant could easily bid above the seat price to join. This completes the expansion of 60 to 100 validators and the seat price settles into an equilibrium. Having 64,000 NEAR does not guarantee that you will have a seat because bidding is a competitive process.

**Comment by DavidIsNEAR** [comment]
Dated - will ensure the Validator team are aware of the upcoming Wiki changes and what's needed to keep it up to date
