### ISSUE TITLE
Broken Link to 'delegation docs' on Validator FAQs

### ISSUE THREAD

**Issue by charleslavon** [near/wiki#205]
The `delegation docs` link from [this page](https://github.com/near/wiki/blob/master/Archive/validators/faq.md#my-stake-has-been-delegated-but-rewards-arent-showing-up-how-do-i-see-them) is broken. It leads to Gitbook, which requires a login, then upon login it leads to an error/blankpage. 

<img width="823" alt="Screen Shot 2023-10-06 at 23 56 07" src="https://github.com/near/wiki/assets/1915116/601ce2f6-fdaa-4b3f-89c9-b20c9db37cdb">

Note: This FAQ page contains other links titled `delegation docs`, they all lead to the current page @ `https://github.com/near/wiki/blob/master/Archive/validators/faq.md#` and are unhelpful.

**Comment by humanman** [comment]
@charleslavon this is fixed now. Should update to the live site within 5 minutes
