### ISSUE TITLE
Missing the doc about balance changes #43

### ISSUE THREAD

**Issue by humanman** [near/wiki#71]

**Comment by humanman** [comment]
[telezhnaya](https://github.com/telezhnaya) can you confirm this is the page? https://wiki.near.org/overview/tokenomics/balance

I’m not sure why it’s not indexed in the search. I’ll make a new issue for that.

**Comment by telezhnaya** [comment]
Yes, that's the page. Let's keep this open until we fix the search

**Comment by humanman** [comment]
The search functionality runs a crawler once every 24 hours to re-index content. So, I'll keep an eye on it for the next few hours to see if it fixes itself.

**Comment by humanman** [comment]
this should be working as expected now: https://share.getcloudapp.com/z8ul2Ed9

**Comment by telezhnaya** [comment]
Yay, it works! Thank you
